name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: Terraform Apply - DEV
    runs-on: ubuntu-latest

    environment: dev

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ vars.DEV_AWS_ACCOUNT_ID }}:role/${{ vars.DEV_AWS_ROLE_NAME }}
          aws-region: ${{ vars.DEV_AWS_REGION }}

      - name: Verify AWS account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          echo "Expected AWS Account: ${{ vars.DEV_AWS_ACCOUNT_ID }}"
          echo "Actual AWS Account:   $ACCOUNT_ID"

          if [ "$ACCOUNT_ID" != "${{ vars.DEV_AWS_ACCOUNT_ID }}" ]; then
            echo "ERROR: Incorrect AWS account!"
            exit 1
          fi

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve